# Generated by Django 2.2.24 on 2023-02-11 08:22

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('tipe_event', models.CharField(max_length=50)),
                ('tema_event', models.CharField(max_length=75)),
                ('penyelenggara', models.CharField(max_length=64)),
                ('nama_event', models.CharField(max_length=110)),
                ('event_pic', models.FileField(default='', upload_to='')),
                ('event_banner', models.FileField(default='', upload_to='')),
                ('biaya', models.FloatField()),
                ('tanggal_awal_pendaftaran', models.DateField()),
                ('tanggal_akhir_pendaftaran', models.DateField()),
                ('tanggal_event', models.DateField()),
                ('nomor_durasi', models.CharField(max_length=10)),
                ('jenis_durasi', models.CharField(max_length=10)),
                ('jurusan_eligible', models.CharField(max_length=100)),
                ('angkatan_eligible', models.CharField(max_length=100)),
                ('tautan_lanjutan_1', models.URLField(max_length=100)),
                ('tautan_detail_1', models.CharField(max_length=50)),
                ('tautan_lanjutan_2', models.URLField(max_length=100)),
                ('tautan_detail_2', models.CharField(max_length=50)),
                ('tautan_lanjutan_3', models.URLField(max_length=100)),
                ('tautan_detail_3', models.CharField(max_length=50)),
                ('persyaratan_1', models.CharField(default='', max_length=50)),
                ('persyaratan_2', models.CharField(default='', max_length=50)),
                ('persyaratan_3', models.CharField(default='', max_length=50)),
                ('persyaratan_4', models.CharField(default='', max_length=50)),
                ('persyaratan_5', models.CharField(default='', max_length=50)),
                ('persyaratan_6', models.CharField(default='', max_length=50)),
                ('benefit_event_1', models.CharField(default='', max_length=100)),
                ('benefit_event_2', models.CharField(default='', max_length=100)),
                ('benefit_event_3', models.CharField(default='', max_length=100)),
                ('benefit_event_4', models.CharField(default='', max_length=100)),
                ('benefit_event_5', models.CharField(default='', max_length=100)),
                ('benefit_event_6', models.CharField(default='', max_length=100)),
                ('deskripsi', ckeditor_uploader.fields.RichTextUploadingField()),
                ('alumni', models.IntegerField(default=0)),
                ('venue', models.CharField(max_length=50)),
                ('narahubung', models.CharField(max_length=110)),
                ('narahubung_pic', models.FileField(default='', upload_to='')),
                ('narahubung_desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('siswa_terdaftar', models.IntegerField(default=0)),
                ('membutuhkan_pendaftaran', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
