# Generated by Django 2.2.24 on 2023-02-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventrecord',
            old_name='siswa_terdaftar',
            new_name='registered_student',
        ),
    ]
