# Generated by Django 2.2.24 on 2023-02-11 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(default='0000000000', max_length=16)),
                ('nama_sekolah', models.CharField(default='SMK Negeri 4 Bandung', max_length=50)),
                ('jurusan', models.CharField(default='Other', max_length=5)),
                ('tahun_masuk', models.CharField(default='2022', max_length=10)),
                ('tahun_lulus', models.CharField(default='2025', max_length=10)),
                ('telepon', models.CharField(default='089800000000', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
